# Generated by Django 4.0.2 on 2022-03-27 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resturaunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('name', models.TextField()),
                ('long', models.IntegerField()),
                ('lat', models.IntegerField()),
                ('email', models.TextField()),
                ('website', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='zipToCoord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.TextField()),
                ('lat', models.TextField()),
                ('long', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('description', models.TextField()),
                ('title', models.TextField()),
                ('resturaunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaf.resturaunt')),
            ],
        ),
    ]
