# Generated by Django 4.0.2 on 2022-03-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zipToCoord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.TextField()),
                ('lat', models.TextField()),
                ('long', models.TextField()),
            ],
        ),
    ]
