# Generated by Django 4.0.2 on 2022-03-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturaunt',
            name='lat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resturaunt',
            name='long',
            field=models.TextField(),
        ),
    ]
