# Generated by Django 4.0.2 on 2022-03-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0002_rename_creater_resturaunt_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='img',
            field=models.URLField(default=''),
        ),
    ]
